Skopiuj cele ze statutu HS Pomorze
hakierspejs/statut pull request #26
Opened 2020-10-13 19:11 UTC by d33tah

2020-10-17 14:35 UTC, nuke3 approved these changes

2020-10-17 14:35 UTC, nuke3 commented on README.md
OKi

2020-10-20 20:15 UTC, kpc21 approved these changes

2020-10-21 06:52 UTC, thinkofher requested changes, later dismissed

2020-10-21 06:52 UTC, thinkofher commented on README.md
> +e) Upowszechnianie i ochrona wolności osobistej i gospodarczej.
Połączyłbym **d)** i **e)** i wywalił wolność gospodarczą. Efekt:

> d) Upowszechnienie i ochrona praw człowieka, swobód obywatelskich oraz wolności osobistej.

2020-10-21 07:17 UTC, d33tah commented on README.md
> +e) Upowszechnianie i ochrona wolności osobistej i gospodarczej.
@thinkofher na ile jesteś przywiązany do tej propozycji? :"P Bo problem jest taki, że każda kolejna zmiana statutu opóźnia moment, kiedy możemy go zgłosić do prawnika, bo trzeba ją przegłosować itd.

2020-10-27 18:50 UTC, ksiezak approved these changes

2020-10-27 19:13 UTC, kpc21 approved these changes

2020-10-27 20:06 UTC, pmysl approved these changes

2020-10-27 20:08 UTC, merged