Limit 64PLN, usunąć miesięczny limit
hakierspejs/statut pull request #46
Opened 2020-11-11 15:37 UTC by d33tah

Fixes #43 and #38.

2020-11-11 15:45 UTC, pmysl approved these changes

2020-11-11 15:49 UTC, kpc21 approved these changes

2020-11-11 17:54 UTC, ksiezak reviewed
Nie za mały ten limit?

Myślę, że całkowicie bezpiecznie jest dać limit na przynajmniej 100zł. Wtedy członek zarządu najwyżej roztrwoni własną składkę.

W związku jednak, z tym że spodziewam się, że do zarządu nie będą wybierani idioci (a praktyka, przynajmniej na razie pokazuje, że mam rację), to limit mógłby być nawet wyższy. 

W HSwaw jest to 1024zł, jednak HSwaw działa na większą skalę. We Wrocławiu to 64zł, a Silesia ma podobnie jak HSwaw 1024zł.

W związku z powyższym proponuję dać 512zł i zrewidować po 2 latach.

2020-11-11 17:58 UTC, kpc21 commented
@ksiezak nie koniecznie tylko składkę. Wyda 64 zł w poniedziałek, 64 zł we wtorek i już będzie więcej, niż składka.

2020-11-11 18:02 UTC, d33tah commented
![image](https://user-images.githubusercontent.com/295322/98847387-77c03180-2450-11eb-9a85-9eee28e41199.png)

2020-11-11 18:02 UTC, d33tah commented
> Natomiast dla formalności nie dam approvala, przekonaj mnie lub kogoś innego. xD

2020-11-15 01:22 UTC, ksiezak requested changes
W głosowaniu wygrała opcja 128zł.

2020-11-15 11:35 UTC, kpc21 commented
> W głosowaniu wygrała opcja 128zł.

Zmiana wprowadzona. W takim razie chyba możesz dać approve?

2020-11-15 20:28 UTC, d33tah commented
Biorąc pod uwagę, że miało miejsce głosowanie i taka opcja wygrała, korzystając z moich przywilejów administratora merguję te zmiany.

2020-11-15 20:28 UTC, merged